### ISSUE TITLE
publish without the @ scope

### ISSUE THREAD

**Issue by newdawnguitar** [vanruesc/vanruesc-grunt-esdoc#1]
Can you publish this on npm without the @ scope? This is far better than the grunt-esdoc alternative (which doesnt even seem to use the plugin), and I want to use it for my project, but we can't install any scoped packages. If you were to publish this to npm, our org would totally use it.

Thanks!

**Comment by vanruesc** [comment]
I was hoping that @cleversoap would eventually continue his work on [grunt-esdoc](https://github.com/cleversoap/grunt-esdoc), but that project really seems to be dead now, doesn't it.

I agree that it's time to move on - let's get rid of the scope. Do you have any name suggestions? `grunt-esdoc` is taken after all. Maybe something similar to the `grunt-contrib` infix could work.

I'll give this some thought, but first I need to get some sleep 😄

**Comment by vanruesc** [comment]
How does `grunt-plugin-esdoc` sound?

**Comment by newdawnguitar** [comment]
Sounds good to me! I also like the `grunt-contrib-esdoc` idea you had.

**Comment by vanruesc** [comment]
Unfortunately, `grunt-contrib` is reserved for plugins that are [maintained by the Grunt team](https://gruntjs.com/creating-plugins#naming-your-task).

I think we can't go wrong with `grunt-plugin-esdoc` since it's descriptive and neutral. Other tools such as Rollup also use [this naming scheme for their plugins](https://www.npmjs.com/search?q=rollup-plugin&page=1&ranking=optimal).

I'll go ahead and change the name later today if there are no objections until then. I've also prepared some general improvements for the 1.0.0 release 👌

**Comment by newdawnguitar** [comment]
Ah, I didn't know about that restriction.

Well, no objections then! You've done a great job on this! Glad to see it getting officially pushed out!
